services:  
  ollama:
    container_name: ollama-server
    image: ollama/ollama:latest  # Пример Docker-образа Ollama
    ports:
      - "11434:11434"  # Порт, на котором Ollama будет слушать
    networks:
      - todoistNetwork

  telegram-bot:
    container_name: telegram-bot
    depends_on:
      - ollama
    build:
      context: .
    networks:
      - todoistNetwork
    env_file:
      - ".env" 

networks:
  todoistNetwork:
    external: True