services:  
  ollama:
    container_name: ollama-server
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  
    networks:
      - todoistNetwork
    volumes:
      - ollama:/root/.ollama

  telegram-bot:
    container_name: telegram-bot
    depends_on:
      - ollama
    build:
      context: .
    networks:
      - todoistNetwork
    env_file:
      - ".env" 

networks:
  todoistNetwork:
    external: True

volumes:
  ollama: